# Enter your Discord Webhook URL here. If you dont know how or where to get a Webhook in Discord, check this link: https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks

discord:
  webhook-url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL_HERE"