# Enter your Discord Webhook URL here. If you don't know how or where to get a Webhook in Discord, check this link: https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks

discord:
  webhook-url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL_HERE"

messages:
  reloadmessage: "§bJoinLeaveLog §8» §aConfiguration File reloaded!"
  nopermission: "§bJoinLeaveLog §8» §cYou don't have permission for this action!"
  reloadfailed: "§bJoinLeaveLog §8» §cConfiguration File couldn't be reloaded! See console for more information!"